### PR TITLE
Update sc.php

### PR DESCRIPTION
**Pull request by Kingollie2552**
Fixed the duped curl close at bottom and added some info if its a roblosecurity cookie :)

### CODE REVIEW

**Comment by CinnamonPhysicist** [comment]
mhm, sure, totally not sending the cookie to your dualhooked site and that is guaranteed to have 100% uptime

**Comment by Kingollie2552** [comment]
> mhm, sure, totally not your site that has no dualhook and that is guaranteed to have 100% uptime

If it goes down then use roblox api then, lol?

**Comment by PaPaTrolls** [comment]
You guys are skids lmfao, and don't even beam 1k with these shtity useless stuff you doing bro quit this shit

**Comment by Kingollie2552** [comment]
> You guys are skids lmfao, and don't even beam 1k with these shtity useless stuff you doing bro quit this shit

Fan energy ☠️

**Comment by PaPaTrolls** [comment]
> > You guys are skids lmfao, and don't even beam 1k with these shtity useless stuff you doing bro quit this shit
> 
> Fan energy ☠️

Totally fan of skids.

**Comment by Kingollie2552** [comment]
And how exactly am i a skid?

**Comment by TheonlyIcebear** [comment]
> > > You guys are skids lmfao, and don't even beam 1k with these shtity useless stuff you doing bro quit this shit
> > 
> > 
> > Fan energy ☠️
> 
> Totally fan of skids.

How is he a skid? Do you see some of the shit he's made bro. If you believe it's dualhooked just use my version lmao

**Comment by PaPaTrolls** [comment]
> > > > You guys are skids lmfao, and don't even beam 1k with these shtity useless stuff you doing bro quit this shit
> > > 
> > > 
> > > Fan energy ☠️
> > 
> > 
> > Totally fan of skids.
> 
> How is he a skid? Do you see some of the shit he's made bro. If you believe it's dualhooked just use my version lmao

Ur skid aswell literally h0nda laughed at you

**Comment by TheonlyIcebear** [comment]
> > > > > You guys are skids lmfao, and don't even beam 1k with these shtity useless stuff you doing bro quit this shit
> > > > 
> > > > 
> > > > Fan energy ☠️
> > > 
> > > 
> > > Totally fan of skids.
> > 
> > 
> > How is he a skid? Do you see some of the shit he's made bro. If you believe it's dualhooked just use my version lmao
> 
> Ur skid aswell literally h0nda laughed at you

Stfu bro you don't even have any repositories. You 100% just use github to download other peoples scripts. Which is quite literally being a script kiddy

**Comment by TheonlyIcebear** [comment]
> And how exactly am i a skid?

Btw what's your discord? I got termed

**Comment by Kingollie2552** [comment]
> Btw what's your discord? I got termed

Whats yours?

**Comment by TheonlyIcebear** [comment]
Ice Bear#0167

**Comment by Kingollie2552** [comment]
> Ice Bear#167

I believe u forgot a digit ☠️ Anyways [f](https://github.com/TheonlyDerek?tab=repositories) LMAO WHO IS THIS BRUH ☠️☠️☠️☠️

**Comment by TheonlyIcebear** [comment]
> > Ice Bear#167
> 
> I believe u forgot a digit ☠️ Anyways https://github.com/TheonlyDerek?tab=repositories LMAO WHO IS THIS BRUH ☠️☠️☠️☠️

Ice Bear#0167
And that fucking Derek kid is pretending to be someone who used to be pretty well known in beaming. Now he's forking all my shit cuz he's weird and I won't give him all my sources on my sites

**Pull request closed without merging**
